name = "ecurie-notifications-beta"
main = "src/worker.js"
compatibility_date = "2026-07-14"

[vars]
ENVIRONMENT = "beta"
PUSH_ENABLED = "false"
ALLOWED_ORIGIN = "https://damiensiri.github.io,http://127.0.0.1:8000"

[[d1_databases]]
binding = "DB"
database_name = "ecurie-notifications-beta"
database_id = "c88d9f28-f645-4c61-abd2-3ddebcbc0cab"
