import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Miniflare } from 'miniflare';
import worker, {instrumentD1,createRequestDiagnostics,loadPlanning} from '../src/worker.js';
import {processHorseReminders,resolveHealthMail,reminderOffsets} from '../src/horse-health.js';
import {validateBookingHorses} from '../src/paddock-horses.js';
import {photoConfig,signedHorsePhoto,readPhoto} from '../src/horses.js';

const read = name => readFile(new URL('../migrations/'+name,import.meta.url),'utf8');
const split = sql => (sql.replace(/--[^\n]*/g,'').match(/\s*CREATE TRIGGER[\s\S]*?END;|[^;]+;/g)||[]).map(s=>s.trim()).filter(Boolean);
async function execute(db,sql){return db.batch(split(sql).map(s=>db.prepare(s)));}
const payload={name:'Tornado',status:'active',birthDate:null,publicNotes:'Visible',adminNotes:'Secret administratif',ownerIds:[1,2]};
const config={HORSE_PHOTO_TTL_SECONDS:'600',HORSE_PHOTO_BUCKET:'ecurie-products-beta',R2_ACCOUNT_ID:'test',R2_HORSE_ACCESS_KEY_ID:'test',R2_HORSE_SECRET_ACCESS_KEY:'test'};

test('fondations chevaux sur D1 : migration, permissions, conservation, concurrence et budgets',async t=>{
 const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:'horses-test'},r2Buckets:['PRODUCT_IMAGES'],compatibilityDate:'2026-07-14'});
 t.after(()=>mf.dispose());const DB=await mf.getD1Database('DB'), PRODUCT_IMAGES=await mf.getR2Bucket('PRODUCT_IMAGES');
 for(const name of ['0001_users.sql','0002_paddocks.sql','0003_paddock_antiduplicates.sql','0004_paddock_requests.sql','0007_user_approvals.sql','0013_liberte_planning.sql','0020_hour_programs.sql','0021_hour_exceptions.sql','0015_stable_planning.sql','0016_staff_planning.sql','0018_planning_task_employees.sql'])await execute(DB,await read(name));
 await execute(DB,`INSERT INTO users(id,email,first_name,last_name,password_hash,password_salt,password_iterations,created_at,updated_at) VALUES(1,'one@test.invalid','One','Client','x','x',1,'now','now'),(2,'two@test.invalid','Two','Client','x','x',1,'now','now'),(3,'three@test.invalid','Three','Client','x','x',1,'now','now');
 INSERT INTO planning_horses(id,name,active,created_at,updated_at) VALUES(12,'Tornado',1,'now','now'),(18,'Utah',0,'now','now'),(99,'Supprimé',1,'now','now'); DELETE FROM planning_horses WHERE id=99;
 INSERT INTO planning_week_horses VALUES('2026-09-07',12,0);
 INSERT INTO planning_tasks(id,week_start,horse_id,day_index,type,created_at,updated_at) VALUES(50,'2026-09-07',12,0,'travail','now','now');`);
 const before=(await DB.prepare('SELECT * FROM planning_tasks').all()).results;
 await execute(DB,await read('0023_horse_foundations.sql'));
 await execute(DB,await read('0024_horse_planning.sql'));
 await execute(DB,await read('0025_paddock_booking_horses.sql'));
 await execute(DB,await read('0026_horse_health.sql'));
 await execute(DB,await read('0027_horse_health_osteopathy.sql'));
 await execute(DB,await read('0028_planning_pwa_visibility.sql'));
 const afterPlanning=(await DB.prepare('SELECT * FROM planning_tasks').all()).results;
 assert.deepEqual(afterPlanning.map(({source,created_by_user_id,pwa_visible,...row})=>row),before);
 assert.equal(afterPlanning[0].source,'backstage');assert.equal(afterPlanning[0].created_by_user_id,null);
 assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_week_horses').first()).n,1);
 assert.equal((await DB.prepare('SELECT status,active FROM planning_horses WHERE id=18').first()).status,'archived');
 assert.deepEqual((await DB.prepare('PRAGMA foreign_key_check').all()).results,[]);
 for(const id of [1,2,3]){const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('client'+id)));let binary='';for(const byte of digest)binary+=String.fromCharCode(byte);const hash=btoa(binary);await DB.prepare("INSERT INTO user_sessions(user_id,token_hash,created_at,expires_at) VALUES(?,?,'now','2099-01-01')").bind(id,hash).run();}
 const REALTIME_HUB={idFromName:()=>({}),get:()=>({fetch:async()=>new Response(null,{status:204})})};
 const env={DB,PRODUCT_IMAGES,REALTIME_HUB,ADMIN_TOKEN:'admin',...config};
 const call=async(path,{method='GET',body,token='admin',headers={}}={})=>{const pending=[];const response=await worker.fetch(new Request('https://test.invalid'+path,{method,headers:{authorization:'Bearer '+token,...(body?{'content-type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}),env,{waitUntil:p=>pending.push(p)});await Promise.all(pending);return {status:response.status,data:await response.json()};};
 const created=await call('/api/admin/horses',{method:'POST',body:payload});assert.equal(created.status,201);const id=created.data.id;assert.ok(id>99);
 assert.deepEqual((await DB.prepare('SELECT horse_id,user_id FROM horse_owners ORDER BY user_id').all()).results,[{horse_id:id,user_id:1},{horse_id:id,user_id:2}]);
 await t.test('aucune fusion des homonymes et pas de création partielle pour propriétaire invalide',async()=>{assert.equal((await call('/api/admin/horses',{method:'POST',body:payload})).status,201);const n=(await DB.prepare('SELECT COUNT(*) n FROM planning_horses').first()).n;assert.equal((await call('/api/admin/horses',{method:'POST',body:{...payload,ownerIds:[1,999]}})).status,400);assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_horses').first()).n,n);});
 await t.test('lecture client cloisonnée sans données privées',async()=>{const own=await call('/api/me/horses/'+id,{token:'client1'});assert.equal(own.status,200);assert.equal(own.data.horse.publicNotes,'Visible');for(const field of ['adminNotes','owners','photo_key','version'])assert.equal(field in own.data.horse,false);assert.equal((await call('/api/me/horses/'+id,{token:'client3'})).status,404);assert.equal((await call('/api/admin/horses/'+id,{token:'client1'})).status,401);assert.equal((await call('/api/me/horses/'+id,{method:'PATCH',body:payload,token:'client1'})).status,403);});
 await t.test('statuts et retrait de vue conservent les événements ; création hors vue',async()=>{assert.equal((await call('/api/admin/planning/weeks/2026-09-07/horses/12',{method:'DELETE'})).status,200);assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_tasks WHERE id=50').first()).n,1);const taskCreated=await call('/api/admin/planning/tasks',{method:'POST',body:{weekStart:'2026-09-07',horseId:12,dayIndex:1,type:'repos'}});assert.equal(taskCreated.status,201,JSON.stringify(taskCreated.data));const edit=await call('/api/admin/horses/12',{method:'PATCH',body:{...payload,status:'departed',version:1}});assert.equal(edit.status,200);assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_tasks WHERE horse_id=12').first()).n,2);assert.equal((await DB.prepare('SELECT active FROM planning_horses WHERE id=12').first()).active,0);assert.equal((await call('/api/admin/horses/12',{method:'PATCH',body:{...payload,status:'archived',version:2}})).status,200);assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_tasks WHERE horse_id=12').first()).n,2);});
 await t.test('modification obsolète refusée sans perte des propriétaires',async()=>{assert.equal((await call('/api/admin/horses/'+id,{method:'PATCH',body:{...payload,ownerIds:[2],version:1}})).status,200);assert.equal((await call('/api/admin/horses/'+id,{method:'PATCH',body:{...payload,ownerIds:[3],version:1}})).status,409);assert.equal((await call('/api/me/horses/'+id,{token:'client1'})).status,404);assert.equal((await call('/api/me/horses/'+id,{token:'client2'})).status,200);});
 await t.test('planning client agrégé, horaires facultatifs et droits selon la source',async()=>{
  const initial=await call('/api/me/horses/'+id+'?week=2026-09-07',{token:'client2'});assert.equal(initial.status,200);assert.equal(initial.data.events.length,0);
  assert.ok(initial.data.activityTypes.every(type=>type.value!=='proprietaire'));
  assert.equal((await call('/api/me/horses/'+id+'/planning/tasks',{method:'POST',token:'client2',body:{date:'2026-09-08',type:'proprietaire'}})).status,400);
  const createdActivity=await call('/api/me/horses/'+id+'/planning/tasks',{method:'POST',token:'client2',body:{date:'2026-09-08',type:'travail',startsAt:'14:00',endsAt:'15:00',description:'Séance légère'}});
  assert.equal(createdActivity.status,201);assert.equal(createdActivity.data.event.source,'client');assert.equal(createdActivity.data.event.canEdit,true);
  const taskId=createdActivity.data.event.sourceId;
  const detail=await call('/api/me/horses/'+id+'?week=2026-09-07',{token:'client2'});assert.equal(detail.data.events.length,1);assert.equal(detail.data.events[0].date,'2026-09-08');
  assert.equal((await call('/api/me/horses/'+id+'/planning/tasks/'+taskId,{method:'PATCH',token:'client1',body:{description:'Interdit'}})).status,404);
  const changed=await call('/api/me/horses/'+id+'/planning/tasks/'+taskId,{method:'PATCH',token:'client2',body:{endsAt:null,description:'Travail à pied'}});assert.equal(changed.status,200);assert.equal(changed.data.event.endsAt,null);
  assert.equal((await call('/api/me/horses/'+id+'/planning/tasks',{method:'POST',token:'client2',body:{date:'2026-09-09',type:'travail',endsAt:'15:00'}})).status,400);
  const backstage=await call('/api/admin/planning/tasks',{method:'POST',body:{weekStart:'2026-09-07',horseId:id,dayIndex:3,type:'repos'}});assert.equal(backstage.status,201);assert.equal(backstage.data.task.source,'backstage');
  const timed=await call('/api/admin/planning/tasks',{method:'POST',body:{weekStart:'2026-09-07',horseId:id,dayIndex:4,type:'travail',startsAt:'13:30'}});assert.equal(timed.status,201);assert.equal(timed.data.task.startsAt,'13:30');assert.equal(timed.data.task.endsAt,'');
  assert.equal((await call('/api/me/horses/'+id+'/planning/tasks/'+backstage.data.task.id,{method:'DELETE',token:'client2'})).status,404);
  assert.equal((await call('/api/me/horses/'+id+'/planning/tasks/'+taskId,{method:'DELETE',token:'client2'})).status,200);
  assert.equal((await call('/api/admin/planning/horses',{method:'POST',body:{weekStart:'2026-09-07',horseId:id}})).status,201);
  const filtered=await call('/api/admin/planning?week=2026-09-07&horse_ids='+id);assert.equal(filtered.status,200);assert.deepEqual(filtered.data.horses.map(h=>h.id),[id]);assert.ok(filtered.data.tasks.every(task=>task.horseId===id));
 });
 await t.test('publication PWA : défaut ON, exceptions, bascule, lots et conservation',async()=>{
  const horseId=(await call('/api/admin/horses',{method:'POST',body:{...payload,name:'Visibilité',ownerIds:[1]}})).data.id;
  const base={weekStart:'2026-09-07',horseId,dayIndex:0};
  const create=async(extra)=>{const r=await call('/api/admin/planning/tasks',{method:'POST',body:{...base,...extra}});assert.equal(r.status,201,JSON.stringify(r.data));return r.data.task};
  const events=async()=>{const r=await call('/api/me/horses/'+horseId+'?week=2026-09-07',{token:'client1'});assert.equal(r.status,200);return r.data.events};
  const work=await create({type:'travail'});assert.equal(work.pwaVisible,true);assert.equal((await events()).length,1);
  await call('/api/admin/planning/tasks/'+work.id,{method:'PATCH',body:{pwaVisible:false}});assert.equal((await events()).length,0);
  assert.equal((await call('/api/admin/planning/tasks/'+work.id,{method:'PATCH',body:{pwaVisible:true}})).status,200);assert.equal((await events()).length,1);
  await call('/api/admin/planning/tasks/'+work.id,{method:'PATCH',body:{description:'Conserver le choix'}});assert.equal((await events()).length,1);
  await call('/api/admin/planning/tasks/'+work.id,{method:'PATCH',body:{pwaVisible:false}});assert.equal((await events()).length,0);
  assert.equal((await call('/api/admin/planning/tasks/'+work.id,{method:'PATCH',body:{pwaVisible:'false'}})).status,400);
  const lesson=await create({type:'cours',pwaVisible:false});assert.equal(lesson.pwaAutomatic,true);
  const competition=await create({type:'concours'});assert.equal((await events()).length,2);
  await call('/api/admin/planning/tasks/'+lesson.id,{method:'PATCH',body:{type:'repos'}});assert.equal((await events()).length,1);
  const manual=await create({type:'paddock',pwaVisible:false,paddock:'Maison',startsAt:'09:00',endsAt:'10:00'});assert.equal(manual.pwaAutomatic,false);assert.equal((await events()).length,1);
  const request=await DB.prepare("INSERT INTO paddock_requests(user_id,name,email,date,status,created_at,updated_at) VALUES(1,'Test','test@example.invalid','2026-09-13','accepted','now','now') RETURNING id").first();
  const linked=await create({type:'paddock',pwaVisible:false,paddock:'Maison',startsAt:'10:00',endsAt:'11:00',requestId:request.id});assert.equal(linked.pwaAutomatic,true);assert.equal((await events()).length,2);
  await call('/api/admin/planning/tasks/'+linked.id,{method:'PATCH',body:{requestId:null}});assert.equal((await events()).length,1);
  for(const pwaVisible of [false,true]){const r=await call('/api/admin/planning/tasks/batch',{method:'POST',body:{...base,type:'longe',dayIndexes:[1,2],pwaVisible}});assert.equal(r.status,201,JSON.stringify(r.data));}
  assert.equal((await events()).length,3);
  const personal=await call('/api/me/horses/'+horseId+'/planning/tasks',{method:'POST',token:'client1',body:{date:'2026-09-08',type:'travail'}});assert.equal(personal.status,201);assert.equal((await events()).length,4);
  await call('/api/admin/planning/horses',{method:'POST',body:{weekStart:'2026-09-07',horseId}});
  const board=await call('/api/admin/planning?week=2026-09-07&horse_ids='+horseId);assert.equal(board.data.tasks.length,9);assert.ok(!board.data.events.some(e=>e.source==='client'));
  assert.equal(board.data.tasks.find(t=>t.id===work.id).pwaVisible,false);
  assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_tasks WHERE horse_id=?').bind(horseId).first()).n,10);
 });
 await t.test('paddocks : sélection groupée, refus atomique, mouvement, concurrence, annulation et agrégation',async()=>{
  const hours=JSON.stringify(Object.fromEntries(['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'].map(day=>[day,{open:'08:00',close:'20:00',closed:false}])));
  for(const paddock of ['maison','grande','beudot'])await DB.prepare("INSERT OR REPLACE INTO paddock_hours(paddock,schedule_json,updated_at) VALUES(?,?,'now')").bind(paddock,hours).run();
  const h1=(await call('/api/admin/horses',{method:'POST',body:{...payload,name:'Paddock One',ownerIds:[1]}})).data.id;
  const h2=(await call('/api/admin/horses',{method:'POST',body:{...payload,name:'Paddock Two',ownerIds:[1]}})).data.id;
  const foreign=(await call('/api/admin/horses',{method:'POST',body:{...payload,name:'Other Owner',ownerIds:[2]}})).data.id;
  const diag=createRequestDiagnostics(new Request('https://test/check'),new URL('https://test/check'));
  assert.deepEqual((await validateBookingHorses({DB:instrumentD1(DB,diag)},[h1,h2],1)).ids,[h1,h2]);assert.equal(diag.d1Count,1);assert.equal(diag.rowsWritten,0);
  const booking={date:'2026-09-08',time:'09:00',duration:60,paddock:'maison',horseIds:[h1,h2]};
  const tasksBefore=(await DB.prepare('SELECT COUNT(*) n FROM planning_tasks').first()).n;
  for(const horseIds of [[h1,foreign],[h1,999999],[h1,h1],['1'],null]){
    const refused=await call('/api/paddocks/reservations',{method:'POST',token:'client1',body:{...booking,horseIds}});
    assert.ok([400,403].includes(refused.status),JSON.stringify(refused));
    assert.equal((await DB.prepare('SELECT COUNT(*) n FROM paddock_reservations').first()).n,0);
  }
  const created=await call('/api/paddocks/reservations',{method:'POST',token:'client1',body:booking});assert.equal(created.status,201,JSON.stringify(created));
  const bookingId=created.data.reservation.id;
  assert.equal((await DB.prepare('SELECT COUNT(*) n FROM paddock_booking_horses').first()).n,2);
  const detail=await call('/api/me/horses/'+h1+'?week=2026-09-07',{token:'client1'});
  assert.equal(detail.data.events.length,1);assert.equal(detail.data.events[0].source,'paddock_booking');assert.equal(detail.data.events[0].canEdit,false);assert.equal(detail.data.events[0].endsAt,'10:00');
  assert.equal((await call('/api/me/horses/'+h2+'?week=2026-09-07',{token:'client1'})).data.events.length,1);
  const list=await call('/api/paddocks/reservations',{token:'client1'});assert.equal(list.data.reservations[0].horses.length,2);assert.equal(list.data.reservations[0].version,1);
  const unchanged=await DB.prepare('SELECT * FROM paddock_reservations WHERE id=?').bind(bookingId).first();
  for(const extra of [{time:'12:00'},{date:'2026-09-20'},{paddock:'grande'},{duration:90},{userId:2}]){
    assert.equal((await call('/api/paddocks/reservations/'+bookingId,{method:'PATCH',token:'client1',body:{version:1,horseIds:[h1],...extra}})).status,403);
  }
  assert.deepEqual(await DB.prepare('SELECT * FROM paddock_reservations WHERE id=?').bind(bookingId).first(),unchanged);
  const move={...booking,date:'2026-09-15',time:'11:00',horseIds:[h2],version:1};
  const path='/api/paddocks/reservations/'+bookingId;
  assert.equal((await call(path,{method:'PATCH',token:'client2',body:move})).status,403);
  assert.equal((await call(path,{method:'PATCH',token:'client1',body:{...move,horseIds:[h2,foreign]}})).status,403);
  assert.equal((await DB.prepare('SELECT date FROM paddock_reservations WHERE id=?').bind(bookingId).first()).date,booking.date);
  assert.equal((await call('/api/admin/paddocks/reservations/'+bookingId,{method:'PATCH',body:move})).status,200);
  assert.equal((await call('/api/admin/paddocks/reservations/'+bookingId,{method:'PATCH',body:move})).status,409);
  assert.equal((await call('/api/me/horses/'+h1+'?week=2026-09-07',{token:'client1'})).data.events.length,0);
  assert.equal((await call('/api/me/horses/'+h2+'?week=2026-09-14',{token:'client1'})).data.events[0].startsAt,'11:00');
  assert.equal((await DB.prepare('SELECT COUNT(*) n FROM paddock_slot_locks WHERE date=?').bind(booking.date).first()).n,0);
  await DB.prepare("INSERT INTO planning_week_horses VALUES('2026-09-14',?,0)").bind(h2).run();
  const admin=await call('/api/admin/planning?week=2026-09-14&horse_ids='+h2);assert.equal(admin.data.events.length,1);assert.equal(admin.data.events[0].horseId,h2);assert.equal(admin.data.tasks.length,0);
  const excluded=await call('/api/admin/planning?week=2026-09-14&horse_ids='+h1);assert.equal(excluded.data.events.length,0);
  // No association is valid and leaves no copied task behind.
  const empty=await call('/api/paddocks/reservations',{method:'POST',token:'client1',body:{...booking,date:'2026-09-16',horseIds:[]}});assert.equal(empty.status,201);
  const conflict=await call('/api/admin/paddocks/reservations/'+bookingId,{method:'PATCH',body:{...move,date:'2026-09-16',version:2}});assert.equal(conflict.status,409);
  const concurrentPath='/api/admin/paddocks/reservations/'+empty.data.reservation.id;
  const raced=await Promise.all(['2026-09-17','2026-09-18'].map(date=>call(concurrentPath,{method:'PATCH',body:{...booking,date,horseIds:[],version:1}})));
  assert.deepEqual(raced.map(r=>r.status).sort(),[200,409]);
  const winner=await DB.prepare('SELECT * FROM paddock_reservations WHERE id=?').bind(empty.data.reservation.id).first();
  const locks=(await DB.prepare('SELECT date FROM paddock_slot_locks WHERE reservation_key=?').bind(winner.lock_key).all()).results;
  assert.equal(locks.length,2);assert.ok(locks.every(lock=>lock.date===winner.date));
  assert.equal((await DB.prepare('SELECT COUNT(*) n FROM planning_tasks').first()).n,tasksBefore);
  const beforeHorsesOnly=await DB.prepare('SELECT * FROM paddock_reservations WHERE id=?').bind(bookingId).first();
  const beforeLocks=(await DB.prepare('SELECT * FROM paddock_slot_locks WHERE reservation_key=?').bind(beforeHorsesOnly.lock_key).all()).results;
  assert.equal((await call(path,{method:'PATCH',token:'client1',body:{version:2,horseIds:[h1,h2]}})).status,200);
  const afterHorsesOnly=await DB.prepare('SELECT * FROM paddock_reservations WHERE id=?').bind(bookingId).first();
  assert.deepEqual(afterHorsesOnly,{...beforeHorsesOnly,version:3});
  assert.deepEqual((await DB.prepare('SELECT * FROM paddock_slot_locks WHERE reservation_key=?').bind(beforeHorsesOnly.lock_key).all()).results,beforeLocks);
  assert.equal((await call(path,{method:'PATCH',token:'client1',body:{version:3,horseIds:[foreign]}})).status,403);
  await DB.prepare("UPDATE planning_horses SET status='archived' WHERE id=?").bind(h2).run();
  await DB.prepare("DELETE FROM planning_week_horses WHERE horse_id=?").bind(h2).run();
  assert.equal((await call('/api/me/horses/'+h2+'?week=2026-09-14',{token:'client1'})).data.events.length,1);
  assert.equal((await call(path,{method:'DELETE',token:'client1'})).status,200);
  assert.equal((await DB.prepare('SELECT COUNT(*) n FROM paddock_booking_horses WHERE booking_id=?').bind(bookingId).first()).n,0);
  assert.equal((await call('/api/me/horses/'+h2+'?week=2026-09-14',{token:'client1'})).data.events.length,0);
  const adminCreated=await call('/api/admin/paddocks/reservations',{method:'POST',body:{...booking,date:'2026-09-19',userId:1,horseIds:[h1]}});
  assert.equal(adminCreated.status,201,JSON.stringify(adminCreated));
  const adminPath='/api/admin/paddocks/reservations/'+adminCreated.data.reservation.id;
  assert.equal((await call(adminPath,{method:'PATCH',body:{...booking,date:'2026-09-20',horseIds:[h1],version:1}})).status,200);
  assert.equal((await call(adminPath,{method:'DELETE'})).status,200);
  assert.deepEqual((await DB.prepare('PRAGMA foreign_key_check').all()).results,[]);
 });
 await t.test('sanitaire : historique, permissions, invalidation atomique, propriétaires, Cron et doublons',async()=>{
  const healthHorse=(await call('/api/admin/horses',{method:'POST',body:{...payload,name:'Santé',ownerIds:[1,2]}})).data.id;
  const base='/api/admin/horses/'+healthHorse+'/health',client='/api/me/horses/'+healthHorse;
  const now=new Date(),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
  const shift=n=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
  const input={type:'vaccine',label:'Vaccin grippe',performedOn:day,nextDueOn:shift(7),comment:'Rappel annuel'};
  const healthEnv={...env,HORSE_HEALTH_MAIL_ENABLED:'true'};
  assert.deepEqual(reminderOffsets({HORSE_REMINDER_OFFSETS:'30,7,0'}),[30,7,0]);assert.throws(()=>reminderOffsets({HORSE_REMINDER_OFFSETS:'-1'}));
  assert.equal((await call(client+'/health',{method:'POST',token:'client3',body:input})).status,404);
  assert.equal((await call(client+'/health',{token:'client3'})).status,404);
  assert.equal((await call(base,{method:'POST',body:{...input,performedOn:'2026-02-30'}})).status,400);
  const created=await call(client+'/health',{method:'POST',token:'client1',body:input});assert.equal(created.status,201,JSON.stringify(created));const record=created.data.record;
  assert.equal((await DB.prepare('SELECT COUNT(*) n FROM horse_notifications WHERE horse_id=?').bind(healthHorse).first()).n,4);
  const detail=await call(client+'?week=2026-09-07',{token:'client1'});assert.equal(detail.data.horse.healthDue[0].nextDueOn,input.nextDueOn);
  for(const method of ['PATCH','DELETE'])assert.equal((await call(client+'/health/'+record.id,{method,token:'client3',body:{...input,version:1}})).status,404);
  const history=await call(client+'/health',{token:'client1'});assert.equal(history.data.records.length,1);assert.equal(history.data.records[0].comment,input.comment);assert.equal('notificationStatus' in history.data.records[0],false);
  const changed=await call(client+'/health/'+record.id,{method:'PATCH',token:'client1',body:{...input,nextDueOn:shift(14),version:1}});assert.equal(changed.status,200);
  assert.equal((await DB.prepare("SELECT COUNT(*) n FROM horse_notifications WHERE record_id=? AND record_version=1 AND status='cancelled'").bind(record.id).first()).n,4);
  assert.equal((await call(base+'/'+record.id,{method:'PATCH',body:{...input,version:1}})).status,409);
  const replacement=await call(base,{method:'POST',body:input});assert.equal(replacement.status,201);const next=replacement.data.record;
  assert.equal((await call(client+'/health',{token:'client1'})).data.records.length,2);
  assert.equal((await DB.prepare('SELECT is_current FROM horse_health_records WHERE id=?').bind(record.id).first()).is_current,0);
  assert.equal((await DB.prepare("SELECT COUNT(*) n FROM horse_notifications WHERE record_id=? AND status='pending'").bind(record.id).first()).n,0);
  const older=await call(base,{method:'POST',body:{...input,performedOn:shift(-20),nextDueOn:shift(20)}});assert.equal(older.data.record.isCurrent,false);
  let calls=0;
  const send=async(e,item)=>{calls++;const resolved=await resolveHealthMail(e,item.id,item.token);assert.equal(resolved.horse_name,'Santé');assert.equal(resolved.label,input.label);
    assert.equal((await call(base+'/'+next.id,{method:'PATCH',body:{...input,nextDueOn:shift(21),version:1}})).status,409);
    assert.equal((await call('/api/admin/horses/'+healthHorse,{method:'PATCH',body:{...payload,name:'Santé',ownerIds:[3],version:1}})).status,409);
    return {sent:true};
  };
  await Promise.all([processHorseReminders(healthEnv,now,send),processHorseReminders(healthEnv,now,send)]);
  assert.equal(calls,2);await processHorseReminders(healthEnv,now,send);assert.equal(calls,2);
  assert.equal((await call('/api/admin/horses/'+healthHorse,{method:'PATCH',body:{...payload,name:'Santé',ownerIds:[2,3],version:1}})).status,200);
  assert.equal((await DB.prepare("SELECT COUNT(*) n FROM horse_notifications WHERE horse_id=? AND user_id=1 AND status='pending'").bind(healthHorse).first()).n,0);
  assert.equal((await call(client+'/health',{method:'POST',token:'client1',body:input})).status,404);
  const pendingForNew=(await DB.prepare("SELECT COUNT(*) n FROM horse_notifications WHERE horse_id=? AND user_id=3 AND status='pending'").bind(healthHorse).first()).n;assert.equal(pendingForNew,2);
  let uncertainCalls=0;await processHorseReminders(healthEnv,now,async()=>{uncertainCalls++;throw Error('timeout after send')});
  await processHorseReminders(healthEnv,now,async()=>{uncertainCalls++;return {sent:true}});assert.equal(uncertainCalls,1);
  assert.equal((await call(client+'/health/'+next.id,{method:'DELETE',token:'client2',body:{version:1}})).status,200);
  assert.equal((await DB.prepare("SELECT COUNT(*) n FROM horse_notifications WHERE record_id=? AND status IN ('pending','failed','uncertain')").bind(next.id).first()).n,0);
  assert.ok(await DB.prepare('SELECT deleted_at FROM horse_health_records WHERE id=?').bind(next.id).first());
  const osteo=await call(client+'/health',{method:'POST',token:'client2',body:{...input,type:'osteopathy',label:'Ostéopathe',nextDueOn:null}});assert.equal(osteo.status,201);assert.equal(osteo.data.record.type,'osteopathy');
  const dental=await call(base,{method:'POST',body:{...input,type:'dental',label:'Dentiste'}});assert.equal(dental.status,201);
  assert.equal((await call('/api/admin/horses/'+healthHorse,{method:'PATCH',body:{...payload,name:'Santé',status:'archived',ownerIds:[2,3],version:2}})).status,200);
  assert.equal((await DB.prepare("SELECT COUNT(*) n FROM horse_notifications WHERE horse_id=? AND status='pending'").bind(healthHorse).first()).n,0);
  assert.equal((await call(client+'/health',{token:'client2'})).status,200);
  assert.deepEqual((await DB.prepare('PRAGMA foreign_key_check').all()).results,[]);
 });
 await t.test('D1 compte les vrais appels first/all/batch et leurs métadonnées',async()=>{const request=new Request('https://test/api/admin/planning');const d=createRequestDiagnostics(request,new URL(request.url));const db=instrumentD1(DB,d);await db.prepare('SELECT id FROM planning_horses LIMIT 1').first();await db.batch([db.prepare('SELECT id FROM planning_horses'),db.prepare('SELECT horse_id FROM horse_owners')]);assert.equal(d.d1Count,3);assert.equal(d.metadataComplete,true);assert.ok(d.rowsRead>0);assert.equal(d.rowsWritten,0);const p=createRequestDiagnostics(request,new URL(request.url));await loadPlanning({DB:instrumentD1(DB,p)},'2026-09-07',true);assert.equal(p.d1Count,6);});
 await t.test('photo : remplacement, refus concurrent et échec D1 préservent les objets référencés',async()=>{
  const put=async(bytes,version,customEnv=env)=>worker.fetch(new Request(`https://test/api/admin/horses/${id}/photo`,{method:'PUT',headers:{authorization:'Bearer admin','content-type':'image/jpeg','if-match':String(version)},body:new Uint8Array(bytes)}),customEnv,{waitUntil(){}});
  let r=await put([255,216,255,224,1],2);assert.equal(r.status,200);const first=(await DB.prepare('SELECT photo_key FROM planning_horses WHERE id=?').bind(id).first()).photo_key;assert.ok(await PRODUCT_IMAGES.get(first));
  assert.equal((await put([255,216,255,224,2],2)).status,409);assert.ok(await PRODUCT_IMAGES.get(first));
  const brokenDB=new Proxy(DB,{get(target,key){if(key==='prepare')return sql=>{const stmt=target.prepare(sql);if(!sql.startsWith('UPDATE planning_horses SET photo_key'))return stmt;return {bind(){return {all:async()=>{throw Error('D1 unavailable');}}}};};return typeof target[key]==='function'?target[key].bind(target):target[key];}});
  assert.equal((await put([255,216,255,224,3],3,{...env,DB:brokenDB})).status,503);assert.equal((await DB.prepare('SELECT photo_key FROM planning_horses WHERE id=?').bind(id).first()).photo_key,first);assert.ok(await PRODUCT_IMAGES.get(first));
  r=await put([255,216,255,224,4],3);assert.equal(r.status,200);assert.equal(await PRODUCT_IMAGES.get(first),null);
  const ownerPut=token=>worker.fetch(new Request(`https://test/api/me/horses/${id}/photo`,{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'image/jpeg','if-match':'4'},body:new Uint8Array([255,216,255,224,5])}),env,{waitUntil(){}});
  assert.equal((await ownerPut('client3')).status,404);
  assert.equal((await ownerPut('client2')).status,200);
  assert.equal((await ownerPut('client2')).status,409);

 });
});

test('durée signée configurable, URL privée sans accès réseau et validation images',async()=>{
 assert.equal(photoConfig({...config,HORSE_PHOTO_TTL_SECONDS:'900'}).ttl,900);
 assert.throws(()=>photoConfig({...config,HORSE_PHOTO_TTL_SECONDS:'0'}));
 const p=await signedHorsePhoto({...config,HORSE_PHOTO_TTL_SECONDS:'900'},'horses/12/abc.jpg',new Date('2026-09-06T10:00:00Z'));
 assert.equal(new URL(p.url).searchParams.get('X-Amz-Expires'),'900');assert.equal(p.expiresAt,'2026-09-06T10:15:00.000Z');
 assert.equal(await signedHorsePhoto({},'horses/12/abc.jpg'),null);
 await assert.rejects(()=>readPhoto(new Request('https://test',{method:'PUT',headers:{'content-type':'image/png'},body:'not an image'})));
 await assert.rejects(()=>readPhoto(new Request('https://test',{method:'PUT',headers:{'content-type':'image/jpeg','content-length':'4000000'},body:'x'})));
});
